### ISSUE TITLE
Tear down

### ISSUE THREAD

**Issue by knownasilya** [knownasilya/ember-highlight#1]
Do we really need to unhighlight on teardown? Seems like it's extra/unnecessary work.

Any users have thoughts on this?

**Comment by villander** [comment]
@knownasilya i installed this addon, but he not working with ember-cli 2.5.0. :(

**Comment by knownasilya** [comment]
Thanks for letting me know. Were there any errors?

**Comment by villander** [comment]
@knownasilya i not found any errors! Just not working. 
I will investigate further. if I find any trace I warn :D

**Comment by knownasilya** [comment]
Are you sure it's the version of ember-cli and not of Ember itself?

**Comment by villander** [comment]
I do not know, but if we do upgrade cli consequently the ember will together. The worst is that there appears no error or warning.

I will try make update in Ember first.

**Comment by villander** [comment]
@knownasilya how use a `addon`  without public it?

I want test in localhost with my project

**Comment by knownasilya** [comment]
you can `npm link` the addon. Inside your project do `npm link ../ember-highlight` (adjust path to your fs).

**Comment by villander** [comment]
I did update of `Ember`. but not back works. Now will update ember-cli of

**Comment by villander** [comment]
@knownasilya your addon works with ember-cli 2.5.0
Only in a project of my company that is not working, but the problem is with the project.
I created several test projects and its addon worked perfectly.

But I was analyzing the code of your addon and I made some improvements of good practice. Look #5  please

**Comment by petey** [comment]
@knownasilya I consistently get errors with this module (v.1.2.6) on ember 2.18.2, specifically when it calls unhighlight. Version 1.2.5 works fine.

```
component.js:63 Uncaught TypeError: this.$(...).unhighlight is not a function
    at Class.unhighlight (component.js:63)
    at Class.<anonymous> (component.js:30)
    at invoke (backburner.js:258)
    at Queue.flush (backburner.js:151)
    at DeferredActionQueues.flush (backburner.js:329)
    at Backburner.end (backburner.js:462)
    at Backburner._run (backburner.js:833)
    at Backburner._join (backburner.js:809)
    at Backburner.join (backburner.js:529)
    at Function.run.join (ember-metal.js:4453)
```

```
    unhighlight: function unhighlight() {
      if (this.$()) {
->      this.$().unhighlight();
      }
    }
```

**Comment by knownasilya** [comment]
I'll add an extra check there to prevent errors, but seems like something isn't working properly.

**Comment by knownasilya** [comment]
Fix should be in v1.2.7

**Comment by petey** [comment]
I have the same issue, except now for calls to `highlight`. It doesn't appear that jquery-highlight is being included as a dependency at all.

**Comment by knownasilya** [comment]
Did you install with `ember install ember-highlight`? If not, please run `ember g ember-highlight`.

**Comment by knownasilya** [comment]
What version of ember-cli are you running?

**Comment by petey** [comment]
I have done that, and jquery-highlight appears in my node_modules list, but not in the resulting app. 
To make sure I don't have anything weird going on in my app, I created a completely new app with `ember init`, ran `ember install ember-highlight`, then `ember serve`. The resulting `vendor.js` has the code for ember-highlight, and your shim, but not the dependent jquery-highlight code. 

```
$ ember version
ember-cli: 3.1.4
node: 8.11.2
os: darwin x64
```

**Comment by knownasilya** [comment]
Your fix was published in v1.2.8
